
name: "server"
mode: "dev"
port: 8888
version: "v0.0.1"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 100
  max_age: 30
  max_backup: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "investment"
  max_open_conns: 200
  max_idle_conns: 50
