
name: "server"
mode: "release"
port: 8888
version: "v0.0.1"

log:
  level: "ERROR"
  filename: "web_app.log"
  max_size: 100
  max_age: 30
  max_backup: 7

mysql:
  host: "Your Database IP adress"
  port: Port
  user: "Your Database username"
  password: "Your Database pwd"
  dbname: "investment"
  max_open_conns: 100
  max_idle_conns: 50
